travis:
  secure:
    BINSTAR_TOKEN: n9WnD8XYP0YigHWDsfDZQq2yBGOwOqoBd5GnTp5fFVaCJpRIu2J3+qSUgXtUDPV9Ic+sBsTDDZ3Nx5O8RVlk/MV5877F3383eJbJDeoESlK2z2CQ1RsiQ73rq8hINRf4oX/tJAozAkwtYXdhuHTCeh5StjBcLzbMty28Druo8yuQmg2P+X0FsKbqUCPfaQruZGkAMGl7rdHDAv+PsGIFxMGo7KsfiymCVDSxSOHPCrQAOPfVeiqFxQP+uYFQCLxrxvJz8YV931CyETf07LfSk8vNunZLXfgsDT71oV7GsMSn9Hq5Zn4R2Ekk4CkcchH6GlFQm01/NU/n+/EXpW82QcdtvRjnmOwVOW2m0yrKgrcK5+tk3Q4qsLfgvId0lT9ftNF2YNTkjJAV+4vfyENnrAul5qJf04y9WNQ9ruJMVt30PgNTkLdFlTi9pu5Dmv/QS6v55+It+FcRCj+yBF0/px3jn/h8f2cCbG8IN/x8ErrG+tTlNBfSoZy/GkMcPy5CRpKou2yxEWI3h293lzaa/myghSlQjnVzUVzscfk4DQ/NtbfnBlbT/BSR/KyiNKaJGKRRhjXUsWxak83ImLZe0MCnfNRBwzU0S7M8w1LRPy9gwl7qxtKN7O16S2zky4swQml8RTn9hhu2EyDLLA2CXYTP3UYyvKALK94WecgnuMA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
